import { test, expect } from '@playwright/test'

/**
 * Lead-create smoke: walks through the UI path a new lead takes from
 * creation to the detail page, asserting that the LCS custom fields
 * (lcs_source, lcs_score) are present.
 *
 * Requires a pre-authenticated storage state (generated by a separate
 * `auth.setup.ts` once Entra test-users are available). For now the test
 * falls back to Frappe's `/api/method/login` with admin creds so the
 * pipeline runs without MSAL configured.
 */

const ADMIN_USER = process.env.LCS_CRM_ADMIN_USER ?? 'Administrator'
const ADMIN_PASS = process.env.LCS_CRM_ADMIN_PASS ?? 'admin'

test.describe('CRM Lead', () => {
  test.beforeEach(async ({ page, context }) => {
    // Minimal login for pre-SSO local runs. Once Entra is wired, remove
    // this block and rely on `storageState` from auth.setup.ts instead.
    await context.request.post('/api/method/login', {
      form: { usr: ADMIN_USER, pwd: ADMIN_PASS },
    })
    await page.goto('/crm/leads')
  })

  test('lead list renders', async ({ page }) => {
    await expect(page.locator('body')).toContainText(/Leads/i)
  })

  test('lead create form exposes LCS custom fields', async ({ page }) => {
    await page.getByRole('button', { name: /create|new lead/i }).first().click()
    // Custom fields installed by lcs_integrations/patches/v1_0.
    await expect(page.locator('[data-fieldname="lcs_source"]')).toBeVisible()
    await expect(page.locator('[data-fieldname="lcs_score"]')).toBeVisible()
  })
})
