<!--
  LCSPilotDetail — Pilot-Treffer-Detail (Doppelklick / „Treffer öffnen" aus der
  Pilot-Liste). Bewusst KEINE Chance-Ansicht: ein Scout-Treffer wird erst durch
  „Als Chance werten" zur Chance. Blöcke: Ausschreibung · Scoutbewertung (KI-
  gekennzeichnet) · Kommentare · Zuweisung/Entscheid. Daten: get_chance.
-->
<template>
  <div class="flex min-h-0 flex-1 flex-col">
    <LayoutHeader>
      <template #left-header>
        <Breadcrumbs :items="[{ label: 'Vertrieb' }, { label: 'CRM' }, { label: __('Pilot'), route: { name: 'LCS Pilot' } }, { label: c.chance_no || __('Hit') }]" />
      </template>
      <template #right-header>
        <a v-if="c.source_url" class="pld-extlink" :href="c.source_url" target="_blank" rel="noopener">{{ __('Original tender') }} ↗</a>
        <Button :label="__('Refresh')" iconLeft="refresh-cw" :loading="chance.loading" @click="chance.reload()" />
      </template>
    </LayoutHeader>

    <div class="pld" v-if="chance.data">
      <div class="pld-inner">
        <div class="pld-head">
          <div>
            <h1 class="pld-title">{{ c.title }}</h1>
            <div class="pld-sub">{{ c.chance_no }}<template v-if="c.company || c.client"> · {{ c.company || c.client }}</template> · {{ c.source_detail || 'Pilot-Scout' }}</div>
          </div>
          <PpPill :tone="statusTone(c.status)">{{ c.status }}</PpPill>
        </div>

        <div class="pld-grid">
          <!-- Ausschreibung -->
          <section class="pld-card">
            <header class="pld-ch">{{ __('Tender') }}</header>
            <dl class="pld-rows">
              <div><dt>{{ __('Source') }}</dt><dd>{{ c.source_detail || 'Pilot-Scout' }}</dd></div>
              <div><dt>{{ __('Country') }}</dt><dd>{{ c.country || '—' }}</dd></div>
              <div><dt>{{ __('Value') }}</dt><dd>{{ eur(c.order_value) }}</dd></div>
              <div><dt>{{ __('Deadline') }}</dt><dd>{{ c.deadline ? fmtDate(c.deadline) : '—' }}</dd></div>
              <div><dt>{{ __('CPV Codes') }}</dt><dd>{{ c.cpv_codes || '—' }}</dd></div>
              <div v-if="c.source_url"><dt>{{ __('Original tender') }}</dt><dd><a class="pld-link" :href="c.source_url" target="_blank" rel="noopener">{{ __('Open') }} ↗</a></dd></div>
            </dl>
            <p v-if="c.description_original" class="pld-desc">{{ c.description_original }}</p>
          </section>

          <!-- Scoutbewertung — KI-generiert -->
          <section class="pld-card">
            <header class="pld-ch">
              {{ __('Scout evaluation') }}
              <span class="pld-ai" :title="__('Generated by the Pilot scout AI')">{{ __('AI-generated') }}</span>
            </header>
            <div class="pld-scorerow">
              <span class="pld-scorebar" :class="scoreClass(scoreVal)"><i :style="{ width: Math.min(100, Math.max(0, scoreVal || 0)) + '%' }" /></span>
              <input type="number" min="0" max="100" class="pld-scorenum" v-model.number="scoreVal" :disabled="savingScore" @change="saveScore" />
              <span class="pld-scoreunit">/ 100</span>
              <PpPill v-if="c.relevance" :tone="relTone(c.relevance)">{{ c.relevance }}</PpPill>
              <span v-if="scoreOverridden" class="pld-manual">{{ __('manually adjusted') }}</span>
            </div>
            <p v-if="c.category" class="pld-cats"><i class="pld-ai-dot" />{{ c.category }}</p>
            <p v-if="c.reasoning" class="pld-why"><i class="pld-ai-dot" />{{ c.reasoning }}</p>
            <p v-if="c.summary_de" class="pld-summary"><i class="pld-ai-dot" />{{ c.summary_de }}</p>
            <p class="pld-ainote">{{ __('Score · relevance · reasoning · summary come from the Pilot scout AI and can be adjusted by the salesperson.') }}</p>
          </section>

          <!-- Zuweisung / Entscheid -->
          <section class="pld-card">
            <header class="pld-ch">{{ __('Sales decision') }}</header>
            <div class="pld-assign">
              <span class="pld-assign-cap">{{ __('Responsible') }}:</span>
              <span class="pld-assignee" :class="{ muted: !c.responsible }">{{ c.responsible || '—' }}</span>
              <select class="pld-sel" :disabled="assigning" @change="onAssign">
                <option value="">{{ __('Assign to …') }}</option>
                <option v-for="u in users" :key="u.value" :value="u.value">{{ u.label }}</option>
              </select>
            </div>
            <div class="pld-acts">
              <button type="button" class="pld-btn is-primary" :disabled="busy" @click="rate">{{ __('Rate as chance') }}</button>
              <button type="button" class="pld-btn" :disabled="busy" @click="dismiss">{{ __('No chance') }}</button>
            </div>
          </section>

          <!-- Kommentare -->
          <section class="pld-card pld-card--wide">
            <header class="pld-ch">{{ __('Comments') }}</header>
            <div class="pld-cadd">
              <textarea v-model="commentInput" rows="2" class="pld-input" :placeholder="__('Add a comment …')" />
              <button type="button" class="pld-btn is-primary" :disabled="!commentInput.trim() || posting" @click="postComment">{{ __('Post') }}</button>
            </div>
            <ul class="pld-clist">
              <li v-for="cm in comments" :key="cm.name" class="pld-citem">
                <div class="pld-cmeta"><b>{{ cm.author }}</b> · {{ cTime(cm.creation) }}
                  <button v-if="cm.mine" type="button" class="pld-cdel" @click="deleteComment(cm)">✕</button>
                </div>
                <div class="pld-ctext" v-html="cm.content" />
              </li>
              <li v-if="!comments.length" class="pld-cempty">{{ __('No comments yet.') }}</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
    <div v-else class="pld-loading">{{ chance.loading ? __('Loading …') : __('Hit not found') }}</div>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { useRouter } from 'vue-router'
import { createResource, call, toast, Breadcrumbs, Button } from 'frappe-ui'
import { cacheGet } from '@/utils/offlineDB'
import LayoutHeader from '@/components/LayoutHeader.vue'
import PpPill from '@/components/pp/PpPill.vue'

const props = defineProps({ id: { type: String, required: true } })
const router = useRouter()

const chance = createResource({ url: 'lcs_integrations.projects.api.get_chance', makeParams: () => ({ name: props.id }), auto: true,
  onError: async () => { try { const c = await cacheGet('LCS Chance', props.id); if (c) chance.data = c } catch (_) {} } })
const c = computed(() => chance.data || {})

// --- Score (KI) editierbar ------------------------------------------------
const scoreVal = ref(0)
const savingScore = ref(false)
const scoreOverridden = ref(false)
watch(() => c.value.name, () => { scoreVal.value = c.value.score ?? 0 }, { immediate: true })
function saveScore() {
  let v = Math.max(0, Math.min(100, Math.round(Number(scoreVal.value) || 0)))
  scoreVal.value = v
  if (v === (c.value.score ?? 0)) return
  savingScore.value = true
  call('lcs_integrations.projects.api.pilot_set_score', { name: props.id, score: v })
    .then(() => { chance.data.score = v; scoreOverridden.value = true; toast({ title: __('Score saved'), icon: 'check-circle', iconClasses: 'text-green-500' }) })
    .catch((e) => { scoreVal.value = c.value.score ?? 0; toast({ title: __('Could not save.'), text: e?.message || '', icon: 'alert-circle', iconClasses: 'text-red-500' }) })
    .finally(() => { savingScore.value = false })
}

// --- Zuweisen -------------------------------------------------------------
const users = ref([])
const assigning = ref(false)
call('lcs_integrations.projects.api.get_pilot_users').then((r) => { users.value = r || [] })
function onAssign(e) {
  const v = e.target.value; e.target.value = ''
  if (!v) return
  assigning.value = true
  call('lcs_integrations.projects.api.pilot_assign', { name: props.id, user: v })
    .then((r) => { chance.data.responsible = r?.responsible || ''; if (r?.status) chance.data.status = r.status; toast({ title: __('Assigned'), icon: 'check-circle', iconClasses: 'text-green-500' }) })
    .catch((err) => toast({ title: __('Could not save.'), text: err?.message || '', icon: 'alert-circle', iconClasses: 'text-red-500' }))
    .finally(() => { assigning.value = false })
}

// --- Entscheid ------------------------------------------------------------
const busy = ref(false)
function rate() {
  busy.value = true
  call('lcs_integrations.projects.api.pilot_rate_as_chance', { name: props.id })
    .then(() => { toast({ title: __('Rated as chance'), icon: 'check-circle', iconClasses: 'text-green-500' }); router.push({ name: 'LCS Pilot' }) })
    .catch((e) => toast({ title: __('Could not save.'), text: e?.message || '', icon: 'alert-circle', iconClasses: 'text-red-500' }))
    .finally(() => { busy.value = false })
}
function dismiss() {
  busy.value = true
  call('lcs_integrations.projects.api.chance_dismiss', { name: props.id })
    .then(() => { toast({ title: __('Dismissed'), icon: 'check-circle', iconClasses: 'text-green-500' }); router.push({ name: 'LCS Pilot' }) })
    .catch((e) => toast({ title: __('Could not save.'), text: e?.message || '', icon: 'alert-circle', iconClasses: 'text-red-500' }))
    .finally(() => { busy.value = false })
}

// --- Kommentare -----------------------------------------------------------
const comments = ref([])
const commentInput = ref('')
const posting = ref(false)
function loadComments() {
  call('lcs_integrations.projects.api.get_item_comments', { doctype: 'LCS Chance', name: props.id }).then((r) => { comments.value = r || [] })
}
loadComments()
function postComment() {
  const t = commentInput.value.trim()
  if (!t) return
  posting.value = true
  call('lcs_integrations.projects.api.add_item_comment', { doctype: 'LCS Chance', name: props.id, content: t })
    .then((cm) => { if (cm && cm.name) comments.value = [cm, ...comments.value]; commentInput.value = '' })
    .catch((e) => toast({ title: __('Could not save.'), text: e?.message || '', icon: 'alert-circle', iconClasses: 'text-red-500' }))
    .finally(() => { posting.value = false })
}
function deleteComment(cm) {
  call('lcs_integrations.projects.api.delete_item_comment', { name: cm.name })
    .then(() => { comments.value = comments.value.filter((x) => x.name !== cm.name) })
    .catch((e) => toast({ title: __('Could not delete.'), text: e?.message || '', icon: 'alert-circle', iconClasses: 'text-red-500' }))
}

// --- Helfer ---------------------------------------------------------------
function statusTone(s) { if (/relevant/i.test(s)) return 'success'; if (/bearbeitung/i.test(s)) return 'warning'; if (/keine/i.test(s)) return 'neutral'; return 'info' }
function relTone(r) { if (/hoch|high/i.test(r)) return 'success'; if (/mittel|medium/i.test(r)) return 'warning'; if (/niedrig|low/i.test(r)) return 'neutral'; return 'info' }
function scoreClass(v) { return v < 50 ? 'is-low' : v < 70 ? 'is-warn' : '' }
function eur(v) { const n = Number(v) || 0; if (n >= 1e6) return (n / 1e6).toLocaleString('de-DE', { maximumFractionDigits: 1 }) + ' M€'; if (n >= 1e3) return Math.round(n / 1e3).toLocaleString('de-DE') + ' k€'; return '€' + Math.round(n) }
function fmtDate(v) { if (!v) return '—'; const d = new Date(String(v).replace(' ', 'T')); return isNaN(d) ? String(v) : new Intl.DateTimeFormat('de-DE', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(d) }
function cTime(v) { if (!v) return ''; const d = new Date(String(v).replace(' ', 'T')); return isNaN(d) ? String(v) : d.toLocaleString('de-DE', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }) }
</script>

<style scoped>
.pld { flex: 1; min-height: 0; overflow-y: auto; background: var(--pp-bg-base); }
.pld-inner { padding: var(--pp-space-6); display: flex; flex-direction: column; gap: var(--pp-space-4); max-width: 1100px; margin: 0 auto; width: 100%; }
.pld-head { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--pp-space-3); }
.pld-title { font-size: var(--pp-fs-18, 18px); font-weight: var(--pp-weight-semibold); color: var(--pp-text-primary); margin: 0; }
.pld-sub { font-size: var(--pp-fs-13, 13px); color: var(--pp-text-tertiary); margin-top: 2px; }
.pld-grid { display: grid; grid-template-columns: 1fr 1fr; gap: var(--pp-space-4); }
.pld-card { background: var(--pp-bg-surface); border: 1px solid var(--pp-border-subtle); border-radius: var(--pp-radius-ui); box-shadow: var(--pp-shadow-xs); padding: var(--pp-space-4); }
.pld-card--wide { grid-column: 1 / -1; }
.pld-ch { display: flex; align-items: center; gap: var(--pp-space-2); font-size: var(--pp-fs-13, 13px); font-weight: var(--pp-weight-semibold); color: var(--pp-text-primary); margin-bottom: var(--pp-space-3); }
.pld-ai { font-size: 10px; font-weight: var(--pp-weight-bold); letter-spacing: 0.04em; text-transform: uppercase; color: var(--pp-brand-primary);
  background: var(--pp-accent-soft, color-mix(in oklab, var(--pp-brand-primary) 12%, transparent)); padding: 2px 7px; border-radius: var(--pp-radius-full); }
.pld-ai-dot { display: inline-block; width: 6px; height: 6px; border-radius: 50%; background: var(--pp-brand-primary); margin-right: 6px; vertical-align: middle; }
.pld-rows { margin: 0; display: grid; grid-template-columns: auto 1fr; gap: 6px 14px; }
.pld-rows > div { display: contents; }
.pld-rows dt { color: var(--pp-text-tertiary); font-size: 12px; }
.pld-rows dd { margin: 0; color: var(--pp-text-primary); font-size: 12px; text-align: right; }
.pld-desc { margin: var(--pp-space-3) 0 0; font-size: 12px; color: var(--pp-text-secondary); line-height: 1.45; }
.pld-link, .pld-extlink { color: var(--pp-brand-primary); text-decoration: none; font-size: 13px; }
.pld-link:hover, .pld-extlink:hover { text-decoration: underline; }
.pld-scorerow { display: flex; align-items: center; gap: var(--pp-space-2); flex-wrap: wrap; margin-bottom: var(--pp-space-2); }
.pld-scorebar { width: 160px; height: 8px; border-radius: var(--pp-radius-full); background: var(--pp-bg-sunken); overflow: hidden; }
.pld-scorebar i { display: block; height: 100%; background: var(--pp-state-success); }
.pld-scorebar.is-warn i { background: var(--pp-state-warning); } .pld-scorebar.is-low i { background: var(--pp-state-danger); }
.pld-scorenum { width: 60px; text-align: center; font-family: inherit; font-size: 14px; font-weight: var(--pp-weight-semibold); padding: 5px 6px; border: 1px solid var(--pp-border-default); border-radius: var(--pp-radius-ui); background: var(--pp-bg-base); }
.pld-scoreunit { font-size: 12px; color: var(--pp-text-tertiary); }
.pld-manual { font-size: 11px; color: var(--pp-text-tertiary); font-style: italic; }
.pld-cats { margin: 4px 0 0; font-size: 12px; color: var(--pp-brand-primary); }
.pld-why, .pld-summary { margin: var(--pp-space-2) 0 0; font-size: 12px; color: var(--pp-text-secondary); line-height: 1.45; }
.pld-ainote { margin: var(--pp-space-3) 0 0; font-size: 11px; color: var(--pp-text-tertiary); font-style: italic; }
.pld-assign { display: flex; align-items: center; gap: var(--pp-space-2); flex-wrap: wrap; margin-bottom: var(--pp-space-3); }
.pld-assign-cap { font-size: 12px; color: var(--pp-text-tertiary); }
.pld-assignee { font-size: 13px; font-weight: var(--pp-weight-medium); color: var(--pp-text-primary); }
.pld-assignee.muted { color: var(--pp-text-tertiary); font-weight: var(--pp-weight-regular); }
.pld-sel, .pld-input { appearance: none; font-family: inherit; font-size: 13px; color: var(--pp-text-primary); padding: 6px 8px; border: 1px solid var(--pp-border-default); border-radius: var(--pp-radius-ui); background: var(--pp-bg-base); }
.pld-input { width: 100%; }
.pld-acts { display: flex; gap: var(--pp-space-2); }
.pld-btn { appearance: none; cursor: pointer; font-family: inherit; font-size: 13px; font-weight: var(--pp-weight-medium); padding: 8px 14px; border: 1px solid var(--pp-border-default); border-radius: var(--pp-radius-ui); background: var(--pp-bg-surface); color: var(--pp-text-secondary); }
.pld-btn.is-primary { background: var(--pp-brand-primary); border-color: var(--pp-brand-primary); color: var(--pp-text-on-accent); }
.pld-btn:disabled { opacity: .5; cursor: default; }
.pld-cadd { display: flex; gap: var(--pp-space-2); margin-bottom: var(--pp-space-3); align-items: flex-start; }
.pld-cadd .pld-btn { flex-shrink: 0; }
.pld-clist { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: var(--pp-space-2); }
.pld-citem { border-top: 1px solid var(--pp-border-subtle); padding-top: var(--pp-space-2); }
.pld-cmeta { font-size: 11px; color: var(--pp-text-tertiary); display: flex; align-items: center; gap: 6px; }
.pld-cmeta b { color: var(--pp-text-secondary); font-weight: var(--pp-weight-semibold); }
.pld-cdel { margin-left: auto; appearance: none; cursor: pointer; border: 0; background: none; color: var(--pp-text-tertiary); font-size: 12px; }
.pld-ctext { font-size: 12px; color: var(--pp-text-primary); line-height: 1.45; margin-top: 2px; }
.pld-cempty { font-size: 12px; color: var(--pp-text-tertiary); }
.pld-loading { padding: var(--pp-space-8); text-align: center; color: var(--pp-text-tertiary); }
@media (max-width: 767px) { .pld-grid { grid-template-columns: 1fr; } }
</style>
